services:
  - type: web
    name: ai-server
    env: docker
    plan: free
    dockerfilePath: ./Dockerfile
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: PIP_NO_CACHE_DIR
        value: 1
      - key: PIP_PREFER_BINARY
        value: 1
      - key: OPENAI_API_KEY
        sync: false
      - key: DEFAULT_MODEL
        value: gpt-4o
      - key: FALLBACK_MODEL
        value: gpt-4o-mini
      - key: MAX_TOKENS
        value: 4000
      - key: TEMPERATURE
        value: 0.7
      - key: DEBUG
        value: false
      - key: FRONTEND_URL
        value: https://your-frontend-url.com
