services:
  - type: web
    name: ai-server
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn main:app -w 4 -k uvicorn.workers.UvicornWorker --bind 0.0.0.0:$PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: OPENAI_API_KEY
        sync: false
      - key: DEFAULT_MODEL
        value: gpt-4o
      - key: FALLBACK_MODEL
        value: gpt-4o-mini
      - key: MAX_TOKENS
        value: 4000
      - key: TEMPERATURE
        value: 0.7
      - key: DEBUG
        value: false
      - key: FRONTEND_URL
        value: https://your-frontend-url.com
